import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.config import Config
from app.db.firestore import FirestoreService
import logging
from datetime import datetime
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

class EmailService:
    """Email service for sending notifications and feedback"""
    
    def __init__(self):
        self.db_service = FirestoreService()
        self.smtp_host = Config.SMTP_HOST
        self.smtp_port = Config.SMTP_PORT
        self.smtp_user = Config.SMTP_USER
        self.smtp_password = Config.SMTP_PASSWORD
        self.from_email = Config.SMTP_USER
        self.from_name = "SkillBridge Suite"
    
    def send_email(self, to_email: str, subject: str, html_content: str, text_content: str = None) -> bool:
        """Send email using SMTP"""
        try:
            if not all([self.smtp_host, self.smtp_user, self.smtp_password]):
                logger.warning("SMTP configuration incomplete, skipping email send")
                return False
            
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = f"{self.from_name} <{self.from_email}>"
            msg['To'] = to_email
            
            # Add text content
            if text_content:
                text_part = MIMEText(text_content, 'plain')
                msg.attach(text_part)
            
            # Add HTML content
            html_part = MIMEText(html_content, 'html')
            msg.attach(html_part)
            
            # Send email
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                server.send_message(msg)
            
            logger.info(f"Email sent successfully to {to_email}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send email to {to_email}: {str(e)}")
            return False
    
    def send_welcome_email(self, user_email: str, user_name: str) -> bool:
        """Send welcome email to new users"""
        try:
            subject = "Welcome to SkillBridge Suite! 🚀"
            
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                    .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }}
                    .content {{ background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }}
                    .button {{ display: inline-block; background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; margin: 20px 0; }}
                    .features {{ background: white; padding: 20px; border-radius: 5px; margin: 20px 0; }}
                    .feature {{ margin: 15px 0; }}
                    .footer {{ text-align: center; margin-top: 30px; color: #666; font-size: 14px; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>Welcome to SkillBridge Suite!</h1>
                        <p>Your AI-powered career development journey starts here</p>
                    </div>
                    <div class="content">
                        <h2>Hi {user_name}! 👋</h2>
                        <p>Welcome to SkillBridge Suite! We're excited to help you accelerate your tech career with AI-powered insights and personalized learning paths.</p>
                        
                        <div class="features">
                            <h3>What you can do with SkillBridge:</h3>
                            <div class="feature">🎯 <strong>Smart Skill Analysis</strong> - Track your technical skills and get AI-powered gap analysis</div>
                            <div class="feature">🗺️ <strong>Personalized Roadmaps</strong> - Get custom learning paths generated by AI for your career goals</div>
                            <div class="feature">💼 <strong>Job Matching</strong> - Discover opportunities that match your skills and aspirations</div>
                            <div class="feature">📚 <strong>Curated Resources</strong> - Access hand-picked learning materials for every skill level</div>
                            <div class="feature">📊 <strong>Progress Tracking</strong> - Monitor your growth with detailed analytics and insights</div>
                        </div>
                        
                        <p>Ready to get started? Complete your profile and add your first skills to unlock personalized recommendations!</p>
                        
                        <a href="https://skillbridge.app/onboarding" class="button">Complete Your Profile</a>
                        
                        <p>If you have any questions, feel free to reach out to our support team. We're here to help you succeed!</p>
                        
                        <p>Best regards,<br>The SkillBridge Team</p>
                    </div>
                    <div class="footer">
                        <p>© 2024 SkillBridge Suite. All rights reserved.</p>
                        <p>You received this email because you signed up for SkillBridge Suite.</p>
                    </div>
                </div>
            </body>
            </html>
            """
            
            text_content = f"""
            Welcome to SkillBridge Suite!
            
            Hi {user_name}!
            
            Welcome to SkillBridge Suite! We're excited to help you accelerate your tech career with AI-powered insights and personalized learning paths.
            
            What you can do with SkillBridge:
            • Smart Skill Analysis - Track your technical skills and get AI-powered gap analysis
            • Personalized Roadmaps - Get custom learning paths generated by AI for your career goals
            • Job Matching - Discover opportunities that match your skills and aspirations
            • Curated Resources - Access hand-picked learning materials for every skill level
            • Progress Tracking - Monitor your growth with detailed analytics and insights
            
            Ready to get started? Complete your profile and add your first skills to unlock personalized recommendations!
            
            Visit: https://skillbridge.app/onboarding
            
            If you have any questions, feel free to reach out to our support team. We're here to help you succeed!
            
            Best regards,
            The SkillBridge Team
            
            © 2024 SkillBridge Suite. All rights reserved.
            """
            
            return self.send_email(user_email, subject, html_content, text_content)
            
        except Exception as e:
            logger.error(f"Failed to send welcome email: {str(e)}")
            return False
    
    def send_roadmap_generated_email(self, user_email: str, user_name: str, role_title: str, milestone_count: int) -> bool:
        """Send notification when AI roadmap is generated"""
        try:
            subject = f"Your {role_title} Learning Roadmap is Ready! 🎯"
            
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                    .header {{ background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }}
                    .content {{ background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }}
                    .button {{ display: inline-block; background: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; margin: 20px 0; }}
                    .stats {{ background: white; padding: 20px; border-radius: 5px; margin: 20px 0; text-align: center; }}
                    .footer {{ text-align: center; margin-top: 30px; color: #666; font-size: 14px; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>🎯 Your Roadmap is Ready!</h1>
                        <p>AI-generated learning path for {role_title}</p>
                    </div>
                    <div class="content">
                        <h2>Hi {user_name}!</h2>
                        <p>Great news! Your personalized learning roadmap for <strong>{role_title}</strong> has been generated using our AI engine.</p>
                        
                        <div class="stats">
                            <h3>Your Roadmap Includes:</h3>
                            <p><strong>{milestone_count} Learning Milestones</strong></p>
                            <p>Curated resources, skill progression, and estimated timelines</p>
                        </div>
                        
                        <p>Your roadmap is tailored to your current skills and experience level, providing a clear path to achieve your career goals.</p>
                        
                        <a href="https://skillbridge.app/roadmap" class="button">View Your Roadmap</a>
                        
                        <p>Start learning today and track your progress as you advance toward your {role_title} goals!</p>
                        
                        <p>Happy learning!<br>The SkillBridge Team</p>
                    </div>
                    <div class="footer">
                        <p>© 2024 SkillBridge Suite. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
            """
            
            return self.send_email(user_email, subject, html_content)
            
        except Exception as e:
            logger.error(f"Failed to send roadmap generated email: {str(e)}")
            return False
    
    def send_feedback_email(self, user_email: str, user_name: str, feedback_type: str, message: str) -> bool:
        """Send feedback/query email to support team"""
        try:
            subject = f"SkillBridge Feedback: {feedback_type} from {user_name}"
            
            # Send to support team (using same SMTP for simplicity)
            support_email = self.from_email  # In production, use dedicated support email
            
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                    .header {{ background: #f59e0b; color: white; padding: 20px; text-align: center; }}
                    .content {{ background: #f9f9f9; padding: 30px; }}
                    .user-info {{ background: white; padding: 15px; border-radius: 5px; margin: 15px 0; }}
                    .message {{ background: white; padding: 20px; border-radius: 5px; margin: 15px 0; border-left: 4px solid #f59e0b; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>New Feedback Received</h1>
                        <p>Type: {feedback_type}</p>
                    </div>
                    <div class="content">
                        <div class="user-info">
                            <h3>User Information:</h3>
                            <p><strong>Name:</strong> {user_name}</p>
                            <p><strong>Email:</strong> {user_email}</p>
                            <p><strong>Feedback Type:</strong> {feedback_type}</p>
                            <p><strong>Submitted:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
                        </div>
                        
                        <div class="message">
                            <h3>Message:</h3>
                            <p>{message}</p>
                        </div>
                    </div>
                </div>
            </body>
            </html>
            """
            
            # Send to support team
            success = self.send_email(support_email, subject, html_content)
            
            if success:
                # Send confirmation to user
                self._send_feedback_confirmation(user_email, user_name, feedback_type)
            
            return success
            
        except Exception as e:
            logger.error(f"Failed to send feedback email: {str(e)}")
            return False
    
    def _send_feedback_confirmation(self, user_email: str, user_name: str, feedback_type: str) -> bool:
        """Send feedback confirmation to user"""
        try:
            subject = "We received your feedback - SkillBridge Support"
            
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                    .header {{ background: #10b981; color: white; padding: 20px; text-align: center; }}
                    .content {{ background: #f9f9f9; padding: 30px; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>Thank You for Your Feedback!</h1>
                    </div>
                    <div class="content">
                        <h2>Hi {user_name}!</h2>
                        <p>Thank you for reaching out to us regarding: <strong>{feedback_type}</strong></p>
                        
                        <p>We've received your message and our team will review it carefully. If your inquiry requires a response, we'll get back to you within 24-48 hours.</p>
                        
                        <p>Your feedback helps us improve SkillBridge Suite for everyone. We appreciate you taking the time to share your thoughts with us.</p>
                        
                        <p>Best regards,<br>SkillBridge Support Team</p>
                    </div>
                </div>
            </body>
            </html>
            """
            
            return self.send_email(user_email, subject, html_content)
            
        except Exception as e:
            logger.error(f"Failed to send feedback confirmation: {str(e)}")
            return False
    
    def send_weekly_progress_email(self, user_email: str, user_name: str, progress_data: Dict) -> bool:
        """Send weekly progress summary email"""
        try:
            subject = "Your Weekly Progress Summary 📊"
            
            skills_added = progress_data.get('skillsAdded', 0)
            resources_completed = progress_data.get('resourcesCompleted', 0)
            roadmap_progress = progress_data.get('roadmapProgress', 0)
            
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                    .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }}
                    .content {{ background: #f9f9f9; padding: 30px; }}
                    .stats {{ display: flex; justify-content: space-around; margin: 20px 0; }}
                    .stat {{ background: white; padding: 20px; border-radius: 5px; text-align: center; flex: 1; margin: 0 10px; }}
                    .stat h3 {{ color: #667eea; margin: 0; font-size: 2em; }}
                    .button {{ display: inline-block; background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; margin: 20px 0; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>📊 Weekly Progress Summary</h1>
                        <p>Your learning journey this week</p>
                    </div>
                    <div class="content">
                        <h2>Hi {user_name}!</h2>
                        <p>Here's a summary of your progress this week on SkillBridge Suite:</p>
                        
                        <div class="stats">
                            <div class="stat">
                                <h3>{skills_added}</h3>
                                <p>Skills Added</p>
                            </div>
                            <div class="stat">
                                <h3>{resources_completed}</h3>
                                <p>Resources Completed</p>
                            </div>
                            <div class="stat">
                                <h3>{roadmap_progress}%</h3>
                                <p>Roadmap Progress</p>
                            </div>
                        </div>
                        
                        <p>Keep up the great work! Consistent learning is the key to achieving your career goals.</p>
                        
                        <a href="https://skillbridge.app/dashboard" class="button">View Full Dashboard</a>
                        
                        <p>Ready for next week? Check out your personalized recommendations and continue your learning journey!</p>
                        
                        <p>Best regards,<br>The SkillBridge Team</p>
                    </div>
                </div>
            </body>
            </html>
            """
            
            return self.send_email(user_email, subject, html_content)
            
        except Exception as e:
            logger.error(f"Failed to send weekly progress email: {str(e)}")
            return False