# Google App Engine configuration (alternative to Cloud Run)
runtime: python311

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Environment variables
env_variables:
  FLASK_ENV: production
  PORT: 8080
  PYTHONPATH: /srv

# Health check
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Network settings
network:
  forwarded_ports:
    - 8080

# Skip files (similar to .dockerignore)
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?tests/.*$
  - ^(.*/)?test_.*\.py$
  - ^(.*/)?.*_test\.py$
  - ^(.*/)?debug_.*\.py$
  - ^(.*/)?venv/.*$
  - ^(.*/)?env/.*$
  - ^(.*/)?__pycache__/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.vscode/.*$
  - ^(.*/)?\.idea/.*$
  - ^(.*/)?README\.md$
  - ^(.*/)?.*\.md$
  - ^(.*/)?Dockerfile$
  - ^(.*/)?docker-compose.*\.yml$
  - ^(.*/)?\.dockerignore$